name: base
channels:
  - conda-forge
  - fastai
  - pytorch
dependencies:
  - gdown
  - python=3.9
  - mamba==0.15.3
  - conda==4.10.3
  - pip
  - voila
  - ca-certificates
  - certifi
  - openssl
  - fastai
  - pymorphy2==0.8
  - ipykernel
  - pytorch
  - torchvision
  - torchaudio
  - cudatoolkit=10.2
  - python-docx
  - ipywidgets
  - scikit-learn